apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, *, *, */*, allow
    g, ORomenska, role:org-admin
    g, test, role:readonly
  scopes: '[groups, preferred_username]'
