apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
patches:
- argocd-cm.yaml
- argocd-rbac-cm.yaml
- argocd-cmd-params-cm.yaml
- argocd-server.yaml
